name: example-nodejs
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      url: https://github.com/gitlawr/pipeline-example-nodejs.git
- name: build
  steps:
  - runScriptConfig:
      image: node:8
      isShell: true
      shellScript: |-
        npm start &
        SERVER=localhost
        npm install
        npm test
